
development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: dummy_development
  pool:     5
  username: manikandandayalan
  password: Federation123
  template: template0
  port: 5432

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: dummy_test
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  port: 5432
