default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: dummy_development
  pool:     5
  username: manikandandayalan
  password: Federation123
  template: template0
  port: 5432

test:
  <<: *default
