name: Continuous integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7']
        gemfile: [rails_6.1]
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # bundler-cache: true
      - name: Setup application
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/dummy_test
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dummy_test
        run: |
          cd spec/dummy
          gem install bundler:2.3.3
          bundle install
          bundle exec rake db:create db:migrate
          cd ../../
      - name: Run tests
        run: bundle exec rake