name: Continuous integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' 
          bundler-cache: true
        - uses: actions/checkout@v2
      - name: Build and run test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/dummy_test
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dummy_test
        run: |
          cd spec/dummy
          gem install bundler:2.3.3
          bundle install
          bundle exec rake db:create db:migrate
          cd ../../
          bundle install
          RAILS_ENV=test bundle exec rake
